### PR TITLE
Includes isUFSArg function

### PR DESCRIPTION
**Pull request by king-mahdi**
Includes just isUFSArg
Test cases are in set_relation_test

### CODE REVIEW

**Comment by mstrout** [comment]
Mahdi, why is the configure file in cloog changing?  If it is being generated by the build process then we probably should not include it in the repository.

Look at the isUFCallTerm code and figure out how you would do it with a visitor design pattern?

**Comment by king-mahdi** [comment]
I just ran:

./configure

once, first time I clone a repository.  Then to test the added codes, I do:

make
make test

So, yes, if any compile related file changing, most probably is because of
configure.

Why should we use visitor? It will just make things more complicated, and I
do not see a point of visitor being more logical.

**Comment by mstrout** [comment]
Mahdi,

Please check our theory that the lib/cloog/configure file is generated by deleting it and seeing if you can still get everything to compile.

We want to use the visitor because it handles all of the traversal of the data structure and therefore saves many lines of code.  Here is approximately what you would need:

```
class VisitorIsUFCallParam : public Visitor {
  private:
    bool mResult;
    int mTupleID;
    bool mSeenTupleVar;

  public:
    VisitorIsUFCallParam(int tupleID) : mTupleID(tupleID), mResult(false), mSeenTupleVar(false {}

    bool returnResult() { return mResult; }

    void visitTupleVarTerm(iegenlib::TupleVarTerm *t) {
        if (t->tvloc()==mTupleID) {
            mSeenTupleVar = true;
        }
    }
    void visitExp(iegenlib::Exp * e) {
        // An expression that is not an inequality or an equality is a parameter to a UFCall.
        if (e->isExpression() and mSeenTupleVar) {
            mResult = true;
        }
        // reset flag for next expression traversal
        mSeenTupleVar=false;
    }
};

void SparseConstraints::isUFCallParam(int tupleID) {
    VisitorIsUFCallParam * v = new VisitorIsUFCallParam(tupleID);
    this->acceptVisitor(v);
    return v->returnResult();
}

```

About 30 lines of code, which is what the above is, is much better than the over 100 lines of code plus adding a lot more into the interface is.

We will be gradually moving all of the functionality over to the visitor design pattern.  Any new stuff should use it.

Thanks,
Michelle

**Comment by king-mahdi** [comment]
I checked configure: it is not created in the build process (it is there
from beginning, and after deleting it, make does not work); what happen is
that my make changes it. Apparently my machine's make is newer. But, I do
not think changes be important, all of them probably related to creating a
more efficient and stable configure file. So, we need it to be there, but I
do not think it would matters which one.

About isUFCallParam: I spend last 2 hours trying to make the code you sent
me to work, meaning, I completely replaced my isUFSArg with your
isUFCallParam. It is not working! after a few tests, I found out that
"mExpType" in Exp class is not getting right value: Expression, Equality,
or Inequality; from the beginning, most of them are not getting any value
at all. Do you want me to right a function that independently correct their
value?!

P.S. the entire code for isUFSArg is only 60 line, and it operates
independently, without any other helper class or function!

**Comment by mstrout** [comment]
Thank you for figuring out the configure.  Now figure out how to take those changes out of your pull request.  You might want to set up your local “git” so that it ignores those files.

Looks like you need to call e->setInequality and e->setEquality in Conjunction::addInequality and Conjunction::addEquality as appropriate.  Also, modify the Exp Constructor so that it initializes mExpType=Expression.

**Comment by king-mahdi** [comment]
Hi

We cannot logically use visitor implementation for isUFCallParam. I fixed
ExpType issue with two extra functions in SparseConstraint and Conjunction,
then noticed that it is still not working! After searching for technical
issues, I noticed a logical issue with visitor! Consider searching for
__tv7 in inequality:

__tv7 - diag(col(__tv5)) - 1

We are searching for __tv7, it is not isUFCallParam, but visitor approach
marks it as isUFCallParam while traversing this inequality. Why?
It visits the first term and marks __tv7 as seen,
then it goes on to visit __tv5,
after when it visits Exp that includes __tv5, we have seen __tv7 already!
And the Exp is an expression!
So, __tv7 is a _isUFCallParam_!!
The problem with visitor approach is that it _traverses_ the string\* in a
DFS fashion that cannot logically work here_. My *isUFSArg_ did not have
this problem because it _does a BFS traverse_.

How do you want to proceed?

**Comment by mstrout** [comment]
Now do a "git pull upstream master" to get the new Visitor and acceptVisitor implementation.

**Comment by king-mahdi** [comment]
isUFCallTerm is now working with visitor. To fix the previous problem, I
added a flag that stores "mSeenTupleVar" in pre-visit of Exp and restores
it in post-visit, this way inner expressions inside a nested expression
will not bother traverse of outer expressions.

Do you want me to read the paper or add the project_out?

**Pull request closed without merging**
